---

- include: "yum/install.yml"

# Jenkins should not be running while we change the configuration
# data, otherwise some files might be overwritten when it restarts
- include: "yum/stop.yml"
- include: "configure-jenkins.yml"
- include_tasks: "configure-nodes.yml"
  with_items:
    - "{{ jenkins_nodes }}"
  loop_control:
    loop_var: outer_item

- include: "yum/restart.yml"
- include: "wait-for-start.yml"
- include: "configure-plugins.yml"

- include: "configure-jobs.yml"
- include: "{{ jenkins_after_config_jobs_file | default('empty.yml') }}"
