- name: "Make sure Jenkins is stopped"
  service: name="jenkins" state="stopped"
  ignore_errors: yes

- name: "Create Jenkins group"
  group:
    name: "{{ jenkins_config_group }}"
    state: present

- name: "Create Jenkins user"
  user: 
    name: "{{ jenkins_config_owner }}" 
    groups: "{{ jenkins_config_group }}"
    generate_ssh_key: yes
    state: "present"

- name: "Install Java and GIT"
  yum: name="{{ item }}" state="present"
  with_items:
    - git

- name: "Install Jenkins"
  yum:
    name: "jenkins-{{ jenkins_version }}"
    state: present

- name: Set JENKINS_HOME
  lineinfile:
    create: "yes"
    dest: "/etc/sysconfig/jenkins"
    line: "JENKINS_HOME={{ jenkins_home }}"
    regexp: '^JENKINS_HOME='
    state: "present"

- name: "Set Jenkins command line options"
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: '^JAVA_ARGS='
    line: "JAVA_ARGS=\"{{ jenkins_java_opts }}\""
